docusaurus:
  docusaurus:
    env:
      typesenseHost: docs-search.hypelens.de
      typesensePort: "8108"
      typesenseProtocol: http
    image:
      imageTag: d1bd593
      repository: akyriako78/docs-next-preview
  ports:
  - name: http
    port: 80
    targetPort: 80
  replicas: 3
  type: NodePort
kubernetesClusterDomain: cluster.local
