apiVersion: apps/v1
kind: Deployment
metadata:
  name: docusaurus
  namespace: typesense
  labels:
    app: docusaurus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docusaurus
  template:
    metadata:
      labels:
        app: docusaurus
    spec:
      containers:
      - name: docusaurus
        image: akyriako78/docsnext:latest
---
apiVersion: v1
kind: Service
metadata:
  name: docusaurus
  namespace: typesense
spec:
  # type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: docusaurus
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: docusaurus
#   namespace: typesense
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: docusaurus
#             port:
#               number: 80
