apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docusaurus
  name: docusaurus
  namespace: docs-next
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docusaurus
  template:
    metadata:
      labels:
        app: docusaurus
    spec:
      containers:
      - env:
        - name: TYPESENSE_API_KEY
          valueFrom:
            secretKeyRef:
              key: search-api-key
              name: api-keys
        - name: TYPESENSE_HOST
          value: docs-search.hypelens.de
        - name: TYPESENSE_PORT
          value: "8108"
        - name: TYPESENSE_PROTOCOL
          value: http
        image: akyriako78/docsnext:rc.2
        name: docusaurus
