apiVersion: apps/v1
kind: Deployment
metadata:
  name: docusaurus
  namespace: docs-next
  labels:
    app: docusaurus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docusaurus
  template:
    metadata:
      labels:
        app: docusaurus
    spec:
      containers:
        - name: docusaurus
          image: akyriako78/docs-next-preview:latest
          env:
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: search-api-key
            - name: TYPESENSE_HOST
              value: docs-search.hypelens.de
            - name: TYPESENSE_PORT
              value: "8108"
            - name: TYPESENSE_PROTOCOL
              value: http
---
apiVersion: v1
kind: Service
metadata:
  name: docusaurus
  namespace: docs-next
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: docusaurus
