web:
  replicas: 2
  image:
    repository: ghcr.io/umami-software/umami
    tag: postgresql-v2.13.2
  imagePullPolicy: IfNotPresent
postgresql:
  storageClass: default
ingress:
  elbId: 
  host:
  port: 80
  clusterIssuer: opentelekomcloud-letsencrypt-staging
