web:
  replicas: 2
  image:
    repository: ghcr.io/umami-software/umami
    tag: postgresql-v2.13.2
  imagePullPolicy: IfNotPresent
postgresql:
  storageClass: csi-disk
ingress:
  elbId: 
  host:
  port: 443
  clusterIssuer: letsencrypt-prod
