apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy-config
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
data:
  nginxConf: |-
    events {}
    http {
      server {
        listen 80;
        valid_referers server_names {{ .Values.docusaurus.host }};
        if ($invalid_referer) {
          return 403;
        }
        location / {
          proxy_pass http://{{ include "typesense.fullname" . }}-svc:8108/;
          proxy_pass_request_headers on;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy
  labels:
    app: typesense-reverse-proxy
  {{- include "typesense.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.typesenseReverseProxy.replicas }}
  selector:
    matchLabels:
      app: typesense-reverse-proxy
    {{- include "typesense.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: typesense-reverse-proxy
      {{- include "typesense.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.typesenseReverseProxy.typesenseReverseProxy.image.repository
          }}:{{ .Values.typesenseReverseProxy.typesenseReverseProxy.image.tag | default
          .Chart.AppVersion }}
        name: typesense-reverse-proxy
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
      volumes:
      - configMap:
          name: {{ include "typesense.fullname" . }}-reverse-proxy-config
        name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
spec:
  type: {{ .Values.typesenseReverseProxy.type }}
  selector:
    app: typesense-reverse-proxy
  {{- include "typesense.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.typesenseReverseProxy.ports | toYaml | nindent 2 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: {{ .Values.typesenseReverseProxy.elbId }}
    kubernetes.io/elb.port: {{ quote .Values.typesenseReverseProxy.port }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: cce
  rules:
  - host: {{ .Values.typesenseReverseProxy.host }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "typesense.fullname" . }}-reverse-proxy'
            port:
              number: {{ .Values.typesenseReverseProxy.port }}
        path: /
        pathType: ImplementationSpecific