apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docusaurus.fullname" . }}-api-keys
  labels:
  {{- include "docusaurus.labels" . | nindent 4 }}
data:
  typesense-api-key: {{ required "apiKeys.typesenseApiKey is required" .Values.env.typesenseSearchApiKey
    | b64enc | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docusaurus.fullname" . }}-docusaurus
  labels:
    app: docusaurus
  {{- include "docusaurus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: docusaurus
    {{- include "docusaurus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: docusaurus
      {{- include "docusaurus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: REACT_APP_TYPESENSE_API_KEY
          valueFrom:
            secretKeyRef:
              key: typesense-api-key
              name: {{ include "docusaurus.fullname" . }}-api-keys
        - name: REACT_APP_TYPESENSE_HOST
          value: {{ required "env.typesenseHost is required" .Values.env.typesenseHost | quote }}
        - name: REACT_APP_TYPESENSE_PORT
          value: {{ required "env.typesensePort is required" .Values.env.typesensePort | quote }}
        - name: REACT_APP_TYPESENSE_PROTOCOL
          value: {{ required "env.typesenseProtocol is required" .Values.env.typesenseProtocol | quote }}
        image: {{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}-{{ required ".Values.environment is required" .Values.environment }}
        name: docusaurus
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docusaurus.fullname" . }}-docusaurus
  labels:
  {{- include "docusaurus.labels" . | nindent 4 }}
spec:
  selector:
    app: docusaurus
  {{- include "docusaurus.selectorLabels" . | nindent 4 }}
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "docusaurus.fullname" . }}-docusaurus-{{ required "ingress.clusterIssuer is required" .Values.ingress.clusterIssuer }}-certificate
spec:
  dnsNames:
  - {{ required "ingress.host is required" .Values.ingress.host }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ required "ingress.clusterIssuer is required" .Values.ingress.clusterIssuer }}
  secretName: {{ include "docusaurus.fullname" . }}-docusaurus-{{ required "ingress.clusterIssuer is required" .Values.ingress.clusterIssuer }}-certificate-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "docusaurus.fullname" . }}-docusaurus
  labels:
  {{- include "docusaurus.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: {{ required "ingress.elbId is required" .Values.ingress.elbId }}
    kubernetes.io/elb.port: {{ required "ingress.port is required" .Values.ingress.port | quote}}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: cce
  tls:
  - hosts:
      - {{ required "ingress.host is required" .Values.ingress.host }}
    secretName: {{ include "docusaurus.fullname" . }}-docusaurus-{{ required "ingress.clusterIssuer is required" .Values.ingress.clusterIssuer }}-certificate-tls
  rules:
  - host: {{ required "ingress.host is required" .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "docusaurus.fullname" . }}-docusaurus'
            port:
              number: {{ required "ingress.port is required" .Values.ingress.port }}
        path: /
        pathType: ImplementationSpecific