apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docusaurus.fullname" . }}-api-keys
  labels:
  {{- include "docusaurus.labels" . | nindent 4 }}
data:
  typesense-api-key: {{ required "apiKeys.typesenseApiKey is required" .Values.docusaurus.docusaurus.env.typesenseSearchApiKey
    | b64enc | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docusaurus.fullname" . }}-docusaurus
  labels:
    app: docusaurus
  {{- include "docusaurus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.docusaurus.replicas }}
  selector:
    matchLabels:
      app: docusaurus
    {{- include "docusaurus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: docusaurus
      {{- include "docusaurus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: TYPESENSE_API_KEY
          valueFrom:
            secretKeyRef:
              key: typesense-api-key
              name: {{ include "docusaurus.fullname" . }}-api-keys
        - name: TYPESENSE_HOST
          value: {{ quote .Values.docusaurus.docusaurus.env.typesenseHost }}
        - name: TYPESENSE_PORT
          value: {{ quote .Values.docusaurus.docusaurus.env.typesensePort }}
        - name: TYPESENSE_PROTOCOL
          value: {{ quote .Values.docusaurus.docusaurus.env.typesenseProtocol }}
        image: {{ .Values.docusaurus.docusaurus.image.repository }}:{{ .Values.docusaurus.docusaurus.image.imageTag
          | default .Chart.AppVersion }}
        name: docusaurus
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docusaurus.fullname" . }}-docusaurus
  labels:
  {{- include "docusaurus.labels" . | nindent 4 }}
spec:
  selector:
    app: docusaurus
  {{- include "docusaurus.selectorLabels" . | nindent 4 }}
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "docusaurus.fullname" . }}-docusaurus
  labels:
  {{- include "docusaurus.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: {{ .Values.docusaurus.ingress.elbId }}
    kubernetes.io/elb.port: {{ quote .Values.docusaurus.ingress.port }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: cce
  rules:
  - host: {{ .Values.docusaurus.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "docusaurus.fullname" . }}-docusaurus'
            port:
              number: {{ .Values.docusaurus.ingress.port }}
        path: /
        pathType: ImplementationSpecific