apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-docusaurus
  labels:
    app: docusaurus
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.docusaurus.replicas }}
  selector:
    matchLabels:
      app: docusaurus
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: docusaurus
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: TYPESENSE_API_KEY
          valueFrom:
            secretKeyRef:
              key: search-api-key
              name: api-keys
        - name: TYPESENSE_HOST
          value: {{ quote .Values.docusaurus.docusaurus.env.typesenseHost }}
        - name: TYPESENSE_PORT
          value: {{ quote .Values.docusaurus.docusaurus.env.typesensePort }}
        - name: TYPESENSE_PROTOCOL
          value: {{ quote .Values.docusaurus.docusaurus.env.typesenseProtocol }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.docusaurus.docusaurus.image.repository }}:{{ .Values.docusaurus.docusaurus.image.imageTag
          | default .Chart.AppVersion }}
        name: docusaurus
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-docusaurus
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.docusaurus.type }}
  selector:
    app: docusaurus
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.docusaurus.ports | toYaml | nindent 2 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-docusaurus
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: {{ .Values.docusaurus.ingress.elbId }}
    kubernetes.io/elb.port: {{ quote .Values.docusaurus.ingress.port }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: cce
  rules:
  - host: {{ .Values.docusaurus.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-docusaurus'
            port:
              number: {{ .Values.docusaurus.ingress.port }}
        path: /
        pathType: ImplementationSpecific