apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-reverse-proxy-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  nginx.conf: {{ .Values.reverseProxyConfig.nginxConf | toYaml | indent 1 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-typesense-reverse-proxy
  labels:
    app: typesense-reverse-proxy
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.typesenseReverseProxy.replicas }}
  selector:
    matchLabels:
      app: typesense-reverse-proxy
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: typesense-reverse-proxy
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.typesenseReverseProxy.typesenseReverseProxy.image.repository
          }}:{{ .Values.typesenseReverseProxy.typesenseReverseProxy.image.tag | default
          .Chart.AppVersion }}
        name: typesense-reverse-proxy
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
      volumes:
      - configMap:
          name: {{ include "chart.fullname" . }}-reverse-proxy-config
        name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-typesense-reverse-proxy
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.typesenseReverseProxy.type }}
  selector:
    app: typesense-reverse-proxy
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.typesenseReverseProxy.ports | toYaml | nindent 2 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-typesense-reverse-proxy
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 6d5ba18b-c302-4a0d-9951-d678bbad7a54
    kubernetes.io/elb.port: "80"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: cce
  rules:
  - host: docs-search-preview.hypelens.de
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-typesense-reverse-proxy'
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific