apiVersion: v1
kind: ConfigMap
metadata:
  name: reverse-proxy-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        valid_referers server_names preview.hypelens.de;   
        if ($invalid_referer) {  
          return 403;     
        }

        location / {
          proxy_pass http://typesense-svc:8108/;
          proxy_pass_request_headers on;
        }
      }
    }