apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeslist
  namespace: docs-next
data:
  nodes: typesense-0.typesense-headless.docs-next.svc.cluster.local:8107:8108,typesense-1.typesense-headless.docs-next.svc.cluster.local:8107:8108,typesense-2.typesense-headless.docs-next.svc.cluster.local:8107:8108
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
data:
  typesense-api-key: TXljb21wbGV4cGFzc3dvcmQjNjU0Ng==
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: typesense
    service: typesense-headless
  name: typesense
  namespace: docs-next
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: typesense
      service: typesense-headless
  serviceName: typesense-headless
  template:
    metadata:
      labels:
        app: typesense
        service: typesense-headless
    spec:
      containers:
      - name: typesense
        image: typesense/typesense:26.0
        env:
        - name: TYPESENSE_DATA_DIR
          value: "/usr/share/typesense/data"
        - name: TYPESENSE_API_PORT
          value: "8108"
        - name: TYPESENSE_PEERING_PORT
          value: "8107"
        - name: TYPESENSE_NODES
          value: "/usr/share/typesense/nodes"
        - name: TYPESENSE_ENABLE_CORS
          value: "true"
        - name: TYPESENSE_CORS_DOMAINS
          value: "http://preview.hypelens.de,https://preview.hypelens.de,https://docs-search.hypelens.de,http://docs-search.hypelens.de,http://localhost:8081"
        - name: TYPESENSE_RESET_PEERS_ON_ERROR
          value: "true"
        - name: TYPESENSE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: typesense-api-key
        ports:
        - containerPort: 8108
          name: http
        resources:
          limits:
            cpu: 1024m
            memory: 512Mi
          requests:
            cpu: 128m
            memory: 112Mi
        volumeMounts:
        - mountPath: /usr/share/typesense
          name: nodeslist
        - mountPath: /usr/share/typesense/data
          name: data
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 10000
      terminationGracePeriodSeconds: 300
      volumes:
      - configMap:
          items:
          - key: nodes
            path: nodes
          name: nodeslist
        name: nodeslist
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: csi-disk
---
apiVersion: v1
kind: Service
metadata:
  name: typesense-headless
  namespace: docs-next
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8108
    targetPort: 8108
  selector:
    app: typesense