apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeslist
  namespace: typesense
data:
  nodes: typesense-0.typesense-headless.typesense.svc.cluster.local:8107:8108,typesense-1.typesense-headless.typesense.svc.cluster.local:8107:8108,typesense-2.typesense-headless.typesense.svc.cluster.local:8107:8108
