apiVersion: batch/v1
kind: CronJob
metadata:
  name: typesense-scraper
  namespace: typesense
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: typesense-scraper
              image: typesense/docsearch-scraper:0.9.1
              env:
              - name: CONFIG
                valueFrom:
                  configMapKeyRef:
                    name: scraper-config
                    key: config.json
              - name: TYPESENSE_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: api-keys
                    key: typesense-api-key
              - name: TYPESENSE_HOST
                value: blueprints.hypelens.de
              - name: TYPESENSE_PORT
                value: "8108"
              - name: TYPESENSE_PROTOCOL
                value: http
              resources:
                limits:
                  cpu: 1024m
                  memory: 512Mi
                requests:
                  cpu: 128m
                  memory: 112Mi
          restartPolicy: Never
