apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typesense.fullname" . }}-nodeslist
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
data:
  nodes: {{ .Values.nodeslist.nodes | quote }}