apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typesense.fullname" . }}-scraper-config
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.scraperConfig.configJson | quote }}