apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typesense.fullname" . }}-scraper-config
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.scraperConfig.configJson | quote }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "typesense.fullname" . }}-scraper
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - env:
            - name: CONFIG
              valueFrom:
                configMapKeyRef:
                  key: config.json
                  name: {{ include "typesense.fullname" . }}-scraper-config
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: typesense-api-key
                  name: {{ include "typesense.fullname" . }}-api-keys
            - name: TYPESENSE_HOST
              value: {{ quote .Values.scraper.typesenseScraper.env.typesenseHost
                }}
            - name: TYPESENSE_PORT
              value: {{ quote .Values.scraper.typesenseScraper.env.typesensePort
                }}
            - name: TYPESENSE_PROTOCOL
              value: {{ quote .Values.scraper.typesenseScraper.env.typesenseProtocol
                }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
            image: {{ .Values.scraper.typesenseScraper.image.repository }}:{{ .Values.scraper.typesenseScraper.image.tag
              | default .Chart.AppVersion }}
            name: typesense-scraper
            resources: {{- toYaml .Values.scraper.typesenseScraper.resources | nindent
              10 }}
          restartPolicy: Never
  schedule: {{ .Values.scraper.schedule | quote }}