apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy-config
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
data:
  nginx.conf: {{ .Values.reverseProxyConfig.nginxConf | toYaml | indent 1 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy
  labels:
    app: typesense-reverse-proxy
  {{- include "typesense.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.reverseProxy.replicas }}
  selector:
    matchLabels:
      app: typesense-reverse-proxy
    {{- include "typesense.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: typesense-reverse-proxy
      {{- include "typesense.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.reverseProxy.typesenseReverseProxy.image.repository }}:{{ .Values.reverseProxy.typesenseReverseProxy.image.tag
          | default .Chart.AppVersion }}
        name: typesense-reverse-proxy
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
      volumes:
      - configMap:
          name: {{ include "typesense.fullname" . }}-reverse-proxy-config
        name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
spec:
  type: {{ .Values.reverseProxy.type }}
  selector:
    app: typesense-reverse-proxy
  {{- include "typesense.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.reverseProxy.ports | toYaml | nindent 2 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: ddc29f88-5763-497c-b49b-edfeadaf4b8e
    kubernetes.io/elb.port: "80"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: cce
  rules:
  - host: docs-search.hypelens.de
    http:
      paths:
      - backend:
          service:
            name: '{{ include "typesense.fullname" . }}-reverse-proxy'
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific