apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typesense.fullname" . }}-api-keys
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
data:
  search-api-key: {{ required "apiKeys.searchApiKey is required" .Values.apiKeys.searchApiKey
    | b64enc | quote }}
  typesense-api-key: {{ required "apiKeys.typesenseApiKey is required" .Values.apiKeys.typesenseApiKey
    | b64enc | quote }}