api:
  ports:
  - name: http
    port: 8108
    targetPort: 8108
  type: ClusterIP
apiKeys:
  searchApiKey: ""
  typesenseApiKey: ""
dashboard:
  ports:
  - name: http
    port: 80
    targetPort: 80
  replicas: 1
  type: ClusterIP
  typesenseDashboard:
    image:
      repository: ghcr.io/bfritscher/typesense-dashboard
      tag: latest
headless:
  ports:
  - name: http
    port: 8108
    targetPort: 8108
  type: ClusterIP
kubernetesClusterDomain: cluster.local
nodeslist:
  nodes: typesense-0.typesense-headless.docs-next.svc.cluster.local:8107:8108,typesense-1.typesense-headless.docs-next.svc.cluster.local:8107:8108,typesense-2.typesense-headless.docs-next.svc.cluster.local:8107:8108
reverseProxy:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  replicas: 1
  type: ClusterIP
  typesenseReverseProxy:
    image:
      repository: nginx
      tag: alpine
reverseProxyConfig:
  nginxConf: |-
    events {}
    http {
      server {
        listen 80;
        valid_referers server_names docs-next.hypelens.de;
        if ($invalid_referer) {
          return 403;
        }
        location / {
          proxy_pass http://typesense-headless:8108/;
          proxy_pass_request_headers on;
        }
      }
    }
scraper:
  schedule: '*/2 * * * *'
  typesenseScraper:
    env:
      typesenseHost: typesense-headless
      typesensePort: "8108"
      typesenseProtocol: http
    image:
      repository: typesense/docsearch-scraper
      tag: 0.9.1
    resources:
      limits:
        cpu: 1024m
        memory: 512Mi
      requests:
        cpu: 128m
        memory: 112Mi
scraperConfig:
  configJson: '{"index_name":"docs-next","start_urls":["http://docs-next.hypelens.de/"],"sitemap_urls":["http://docs-next.hypelens.de/sitemap.xml"],"sitemap_alternate_links":true,"stop_urls":["/tests"],"selectors":{"lvl0":{"selector":"(//ul[contains(@class,''menu__list'')]//a[contains(@class,
    ''menu__link menu__link--sublist menu__link--active'')]/text() | //nav[contains(@class,
    ''navbar'')]//a[contains(@class, ''navbar__link--active'')]/text())[last()]","type":"xpath","global":true,"default_value":"Documentation"},"lvl1":"header
    h1","lvl2":"article h2","lvl3":"article h3","lvl4":"article h4","lvl5":"article
    h5, article td:first-child","lvl6":"article h6","text":"article p, article li,
    article td:last-child"},"strip_chars":" .,;:#","custom_settings":{"separatorsToIndex":"_","attributesForFaceting":["language","version","type","docusaurus_tag"],"attributesToRetrieve":["hierarchy","content","anchor","url","url_without_anchor","type"]},"conversation_id":["833762294"],"nb_hits":46250}'
typesense:
  replicas: 3
  typesense:
    env:
      typesenseApiPort: "8108"
      typesenseCorsDomains: http://docs-next.hypelens.de,https://docs-next.hypelens.de,https://docs-search.hypelens.de,http://docs-search.hypelens.de,http://localhost:8081
      typesenseDataDir: /usr/share/typesense/data
      typesenseEnableCors: "true"
      typesenseNodes: /usr/share/typesense/nodes
      typesensePeeringPort: "8107"
      typesenseResetPeersOnError: "true"
    image:
      repository: typesense/typesense
      tag: "26.0"
    resources:
      limits:
        cpu: 1024m
        memory: 512Mi
      requests:
        cpu: 128m
        memory: 112Mi
  volumeClaims:
    data:
      requests:
        storage: 10Gi
