apiVersion: apps/v1
kind: Deployment
metadata:
  name: docusaurus
  namespace: docs-next
  labels:
    app: docusaurus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docusaurus
  template:
    metadata:
      labels:
        app: docusaurus
    spec:
      containers:
        - name: docusaurus
          image: akyriako78/docs-next-preview:latest
          env:
            - name: TYPESENSE_API_KEY
              value: ajJRNTFVc0x1aDlndVl0YzR4MTQ3TXY1WDc0ZzRpU0k=
            - name: TYPESENSE_HOST
              value: docs-search.hypelens.de
            - name: TYPESENSE_PORT
              value: "8108"
            - name: TYPESENSE_PROTOCOL
              value: http
---
apiVersion: v1
kind: Service
metadata:
  name: docusaurus
  namespace: docs-next
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: docusaurus
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docusaurus
  namespace: docs-next
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: c7cd3a6b-1f0b-4268-923d-29858fa4b415
    kubernetes.io/elb.port: '80'
spec:
  ingressClassName: cce
  rules:
  - host: docs-next-preview.hypelens.de
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: docusaurus
            port:
              number: 80
        property:
              ingress.beta.kubernetes.io/url-match-mode: STARTS_WITH
