typesense:
  apiKey: 
scraper:
  schedule: '*/2 * * * *'
reverseProxy:
  replicas: 1
  ingress:
    elbId: 
    host: 
    port: 443
    clusterIssuer: opentelekomcloud-letsencrypt
dashboard:
  replicas: 1
docusaurus: 
  externalUrl: 
