name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser for docusaurus
        uses: helm/chart-releaser-action@v1.6.0
        with:
            charts_dir: docusaurus
        env:
            CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser for typesense
        uses: helm/chart-releaser-action@v1.6.0
        with:
            charts_dir: typesense
        env:
            CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"