name: Release Charts

on:
  push:
    branches:
      - refine_workflow

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Remove Releases
        uses: sgpublic/delete-release-action@v1.1
        with:
            release-drop: true
            release-keep-count: 0
            release-drop-tag: true
            pre-release-drop: true
            pre-release-keep-count: 0
            pre-release-drop-tag: true
            draft-drop: true
            draft-drop-count: 0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-releaser 
        uses: helm/chart-releaser-action@v1.6.0
        with:
            skip_existing: false
        env:
            CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"