apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen {{ required "reverseProxy.ingress.port is required" .Values.reverseProxy.ingress.port }};

        valid_referers server_names {{ required "reverseProxy.docusaurus.externalUrl is required" .Values.docusaurus.externalUrl }};   
        if ($invalid_referer) {  
          return 403;     
        }

        location / {
          proxy_pass http://{{ include "typesense.fullname" . }}-svc:8108/;
          proxy_pass_request_headers on;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy
  labels:
    app: typesense-reverse-proxy
spec:
  replicas: {{ .Values.reverseProxy.replicas }}
  selector:
    matchLabels:
      app: typesense-reverse-proxy
  template:
    metadata:
      labels:
        app: typesense-reverse-proxy
    spec:
      containers:
        - name: typesense-reverse-proxy
          image: nginx:alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "typesense.fullname" . }}-reverse-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: typesense-reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "typesense.fullname" . }}-reverse-proxy
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: {{ required "reverseProxy.ingress.elbId is required" .Values.reverseProxy.ingress.elbId }}
    kubernetes.io/elb.port: {{ required "reverseProxy.ingress.port is required" .Values.reverseProxy.ingress.port | quote }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: cce
  rules:
  - host: {{ required "reverseProxy.ingress.host is required" .Values.reverseProxy.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "typesense.fullname" . }}-reverse-proxy
            port:
              number: {{ required "reverseProxy.ingress.port is required" .Values.reverseProxy.ingress.port }}
        path: /
        pathType: ImplementationSpecific
