apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "typesense.fullname" . }}-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "typesense.fullname" . }}-role
  labels:
    app.kubernetes.io/name: {{ include "typesense.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "typesense.fullname" . }}-role-binding
  labels:
    app.kubernetes.io/name: {{ include "typesense.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "typesense.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "typesense.fullname" . }}-service-account
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typesense.fullname" . }}-api-keys
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
data:
  typesense-api-key: {{ required "typesense.apiKey is required" .Values.typesense.apiKey
    | b64enc | quote }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "typesense.fullname" . }}-pdb
  labels:
    app: {{ include "typesense.fullname" . }}-sts
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "typesense.fullname" . }}-sts
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "typesense.fullname" . }}-ts
  labels:
    app: {{ include "typesense.fullname" . }}-sts
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "typesense.fullname" . }}-sts-resolver
  podManagementPolicy: Parallel
  # updateStrategy: {}
  replicas: 3
  selector:
    matchLabels:
      app: {{ include "typesense.fullname" . }}-sts
  template:
    metadata:
      labels:
        app: {{ include "typesense.fullname" . }}-sts
    spec:
      containers:
        - name: peer-resolver
          image: quay.io/opentelekomcloud/typesense-peer-resolver:1.0.2
          command:
            - "/opt/tspr"
            - "-namespace={{ .Release.Namespace }}"
            - "-service={{ include "typesense.fullname" . }}-sts-resolver"
          volumeMounts:
          - name: nodeslist
            mountPath: /usr/share/typesense
        - name: typesense
          image: typesense/typesense:27.1
          env:
          - name: TYPESENSE_API_KEY
            valueFrom:
              secretKeyRef:
                key: typesense-api-key
                name: {{ include "typesense.fullname" . }}-api-keys
          - name: TYPESENSE_NODES
            value: "/usr/share/typesense/nodes"
          - name: TYPESENSE_DATA_DIR
            value: "/usr/share/typesense/data"
          - name: TYPESENSE_API_PORT
            value: "8108"
          - name: TYPESENSE_PEERING_PORT
            value: "8107"
          - name: TYPESENSE_ENABLE_CORS
            value: "true"
          - name: TYPESENSE_CORS_DOMAINS
            value: "http://{{ .Values.docusaurus.externalUrl }},https://{{ .Values.docusaurus.externalUrl }},https://{{ .Values.reverseProxy.ingress.host }},http://{{ .Values.reverseProxy.ingress.host }}, http://localhost:9089"
          - name: TYPESENSE_RESET_PEERS_ON_ERROR
            value: "true"        
          ports:
          - containerPort: 8108
            name: http
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 2
          resources:
            limits:
              cpu: 1024m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 256Mi
          volumeMounts:
          - name: nodeslist
            mountPath: /usr/share/typesense
          - name: data
            mountPath: /usr/share/typesense/data
      serviceAccountName: {{ include "typesense.fullname" . }}-service-account
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 10000
      terminationGracePeriodSeconds: 300
      volumes:
      - name: nodeslist
        emptyDir: {}
      # - name: health
      #   emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ required "typesense.storage.size is required" .Values.typesense.storage.size }}
      storageClassName: {{ required "typesense.storage.storageClassName is required" .Values.typesense.storage.storageClassName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense.fullname" . }}-sts-resolver
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ include "typesense.fullname" . }}-sts
  ports:
  - name: http
    port: 8108
    targetPort: 8108
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense.fullname" . }}-svc
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "typesense.fullname" . }}-sts
  ports:
  - name: http
    port: 8108
    targetPort: 8108